### PR TITLE
Update to 3.30, change default web user, deprecate SHA-1 and conform to upstream changes

### PR DESCRIPTION
**Pull request by emansom**
As per [upstream discussion](https://github.com/h5bp/server-configs-nginx/issues/95), `conf.d` directory is desired and recommended for the project.

### CODE REVIEW

**Review by quinnjr — APPROVED** [review]

**Review by quinnjr — COMMENTED** [review]
Is there actually a necessity for the change to BLAKE2?

**Comment by quinnjr** [comment]
Also please do another commit bumping the package release and adding your name to the comment at the top of the file as a contributor.

**Comment by emansom** [comment]
> Is there actually a necessity for the change to BLAKE2?

It's an [on-going effort](https://research.kudelskisecurity.com/2017/03/06/why-replace-sha-1-with-blake2/) across the industry to adopt more secure hash algorithms that don't [suffer hash collisions](https://www.zdnet.com/article/sha-1-collision-attacks-are-now-actually-practical-and-a-looming-danger/). It has recently been proven that on moderate hardware, spoofing a hash [is feasible](https://news.ycombinator.com/item?id=21979333).

This is important as to not compromise on the security pillars offered by the Arch package system. Which a secure hash algorithm that can be relied on, is a fundamental.

**Comment by emansom** [comment]
> Also please do another commit bumping the package release and adding your name to the comment at the top of the file as a contributor.

Done!

**Pull request merged**
